# Install chinese language
sudo apt-get install language-pack-zh-hans language-pack-gnome-zh-hans language-pack-zh-hans-base language-pack-gnome-zh-hans-base 
sudo apt-get install language-pack-zh-hant language-pack-gnome-zh-hant language-pack-zh-hant-base language-pack-gnome-zh-hant-base 

# Change system language
echo '#  File generated by update-locale\nLANG="en_HK.UTF-8"\nLANGUAGE="en_HK:en"' >> '/etc/default/locale'

# Switch input method system to fcitx
im-config -n fcitx

# Install quick method for fcitx
sudo apt-get install fcitx-table-quick-classic

# Configuring fcitx
# currently not available
